[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
# Install LaTeX dependencies
aptPkgs = ["texlive-xetex", "texlive-fonts-recommended", "texlive-fonts-extra"]